config/routes.rb
Rails.application.routes.draw do
  resources :ledgers, only: [] do
    post 'buy', to: 'ledgers#buy', as: "buy"
    resources :orders, only: [:create, :destroy]
  end
  resources :users
  resources :tickers do
    member do
      post 'fetch_price'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ledger.rb
class Ledger < ApplicationRecord
  belongs_to :user
  belongs_to :ticker
  has_many :orders, dependent: :destroy

  def balance
    self.orders.map {|o| o.amount }.sum
  end

  def total_value
    self.orders.map {|o| o.amount * o.price  }.sum
  end

  def average_price
    self.total_value.to_f / self.balance
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :ledger
end

app/models/ticker.rb
require 'open-uri'
require 'json'

class Ticker < ApplicationRecord
    has_many :ledger, dependent: :destroy 

    def formatted_price
        if self.price.nil? || self.precision.nil?
            0
        else
            "%.2f" % (self.price.to_f / (10**self.precision))
        end
    end

    def fetch_price!
        response = URI.open(self.url).read
        json_respose = JSON.parse(response)
        text_amount = json_respose["data"]["amount"]
        self.set_amount!(text_amount)
        true
    end

    def set_amount!(amount)
        val = amount.to_f * (10 ** self.precision)
        self.price = val.to_i
        self.save!
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ledgers, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ledgers_controller.rb
class LedgersController < ApplicationController

  before_action :set_ledger

  # /ledgers/1/buy/1
  def buy
    price = @ledger.ticker.price
    @ledger.orders.create(price: price, amount: ledger_params[:amount])

    respond_to do |format|
      format.html { redirect_to user_url(@ledger.user), notice: "Buy order created." }
      format.json { head :no_content }
    end
  end

  private

  def set_ledger
    @ledger = Ledger.find(params[:ledger_id])
  end

  def ledger_params
    params.permit(:amount)    
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_ledger #, only: %i[ show edit update destroy ]

  # POST /ledgers/1/orders
  def create
    @ledger.orders.create(order_params)
    respond_to do |format|
      format.html { redirect_to user_url(@ledger.user), notice: "Order was created." }
      format.json { head :no_content }
    end
  end

  # DELETE /ledgers/1/orders/1
  def destroy
    @ledger.orders.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to user_url(@ledger.user), notice: "Order was destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_ledger
    @ledger = Ledger.find(params[:ledger_id])
  end

  def order_params
    params.require(:order).permit(:ledger_id, :amount, :price)
  end
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController
  before_action :set_ticker, only: %i[ fetch_price show edit update destroy ]

  # GET /tickers or /tickers.json
  def index
    @tickers = Ticker.all
  end

  # GET /tickers/1 or /tickers/1.json
  def show
  end

  # GET /tickers/new
  def new
    @ticker = Ticker.new
  end

  # GET /tickers/1/edit
  def edit
  end

  # POST /tickers or /tickers.json
  def create
    @ticker = Ticker.new(ticker_params)

    respond_to do |format|
      if @ticker.save
        format.html { redirect_to @ticker, notice: "Ticker was successfully created." }
        format.json { render :show, status: :created, location: @ticker }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickers/1 or /tickers/1.json
  def update
    respond_to do |format|
      if @ticker.update(ticker_params)
        format.html { redirect_to @ticker, notice: "Ticker was successfully updated." }
        format.json { render :show, status: :ok, location: @ticker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /tickers/1/fetch
  def fetch_price
    respond_to do |format|
      if @ticker.fetch_price!
        format.html { redirect_to @ticker, notice: "Ticker was successfully updated." }
        format.json { render :show, status: :ok, location: @ticker }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /tickers/1 or /tickers/1.json
  def destroy
    @ticker.destroy
    respond_to do |format|
      format.html { redirect_to tickers_url, notice: "Ticker was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticker
      @ticker = Ticker.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ticker_params
      params.require(:ticker).permit(:ticker, :description, :url, :price, :precision)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:login)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ledgers_helper.rb
module LedgersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/tickers_helper.rb
module TickersHelper    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tickertracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ledgers/index.html.erb
<h1>Ledgers#index</h1>
<p>Find me in app/views/ledgers/index.html.erb</p>

app/views/ledgers/show.html.erb
<h1>Ledgers#show</h1>
<p>Find me in app/views/ledgers/show.html.erb</p>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/tickers/_form.html.erb
<%= form_with(model: ticker) do |form| %>
  <% if ticker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticker.errors.count, "error") %> prohibited this ticker from being saved:</h2>

      <ul>
        <% ticker.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :precision %>
    <%= form.text_field :precision %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickers/edit.html.erb
<h1>Editing Ticker</h1>

<%= render 'form', ticker: @ticker %>

<%= link_to 'Show', @ticker %> |
<%= link_to 'Back', tickers_path %>

app/views/tickers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickers</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Description</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickers.each do |ticker| %>
      <tr>
        <td><%= ticker.ticker %></td>
        <td><%= ticker.description %></td>
        <td><%= ticker.url %></td>
        <td><%= ticker.formatted_price %></td>
        <td><%= link_to 'Show', ticker %></td>
        <td><%= link_to 'Edit', edit_ticker_path(ticker) %></td>
        <td><%= link_to 'Destroy', ticker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticker', new_ticker_path %>

app/views/tickers/new.html.erb
<h1>New Ticker</h1>

<%= render 'form', ticker: @ticker %>

<%= link_to 'Back', tickers_path %>

app/views/tickers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker:</strong>
  <%= @ticker.ticker %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticker.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @ticker.url %>
</p>
<p>
  <strong>Price (formatted):</strong>
  <%= @ticker.formatted_price %>
</p>
<p>
  <strong>Price:</strong>
  <%= @ticker.price %>
</p>
<p>
  <strong>Precision:</strong>
  <%= @ticker.precision %>
</p>

<p>
<%= button_to 'Fetch price', fetch_price_ticker_path(@ticker) %>
</p>

<%= link_to 'Edit', edit_ticker_path(@ticker) %> |
<%= link_to 'Back', tickers_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h1>
  <strong>Login:</strong>
  <%= @user.login %>
</h1>
<% @user.ledgers.each do |ledger| %>
  <div class='ledger'>
    <h2> <%= ledger.ticker.ticker %> : <%= ledger.ticker.formatted_price %>
    </h2>
    <p>
      <%= form_with url: ledger_buy_url(ledger) do |form| %>
        <%= form.text_field :amount, value: 0 %>
        <%= form.submit 'Buy' %>
      <% end %>
    </p>
    <table>
      <tr>
        <th> Balance </th>
        <th> Total value </th>
        <th> Average Price </th>
        <th> Date </th>
      </tr>
      <tr>
        <td> <%= ledger.balance %> </td>
        <td> <%= ledger.total_value %> </td>
        <td> <%= "%.2f" % ledger.average_price %> </td>
        <td> <%= Date.today %> </td>
      </tr>
    </table>
    <h3> Orders </h3>
    <table>
      <tr>
        <th> Amount </th>
        <th> Price </th>
        <th> Date </th>
      </tr>
      <% ledger.orders.each do |order| %>
        <tr>
          <td> <%= order.amount %> </td>
          <td> <%= order.price %> </td>
          <td> <%= order.created_at %> </td>
          <td> <%= button_to 'Remove', ledger_order_path(ledger, order), method: 'delete' %> </td>
        </tr>
      <% end %>
    </table>
    <div>
    </div>
  </div>
<% end %>
<%= link_to "Edit", edit_user_path(@user) %> |
<%= link_to "Back", users_path %>